config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "registrations#new"

  # get "home", to: "homepage#index"
  
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "login#new"
  post "sign_in", to: "login#create"
  post "logout", to: "login#logout"

  get "tours", to: "tours#showAllTour"
  get "chosen_tour", to: "tours#showTour"
  post "tours_with_companion", to: "tours#bookTicketWithCompanion"
  post "tours_without_companion", to: "tours#bookTicketWithoutCompanion"

  get "tickets", to: "tickets#showUserTickets"
  get "all_tickets", to: "tickets#showAllTickets"


  get "admin", to: "admin#new"
  post "admin", to: "admin#create"
  post "logout_admin", to: "admin#logout"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/companion.rb
class Companion < ApplicationRecord
    enum gender: [ :m, :f ]
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :user
    belongs_to :tour
end

app/models/tour.rb
class Tour < ApplicationRecord
    has_many :tickets
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    enum gender: [ :m, :f ]
    has_many :tickets
    validates :gender, presence: true
    validates :user_name, presence: true, uniqueness:true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

    def new
    end

    def create
        user = User.find_by(user_name: params[:user_name])
        if user.present? && user.authenticate(params[:password]) && user.is_admin
            session[:user_id] = user.id
            redirect_to tours_path
        else
            flash[:error] = "Invalid user name or password"
            redirect_to admin_path
        end
    end

    def logout
        session[:user_id] = nil
        redirect_to admin_path, notice: "Logged out"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :setCurrentUser

    def setCurrentUser
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end
end

app/controllers/homepage_controller.rb
class HomepageController <  ApplicationController
    before_action :checkUser

    def checkUser
        if session[:user_id]==nil
            redirect_to sign_up_path, notice: "Logged Out"
        else
            # redirect_to sign_up_path, notice: "Logged Out"
            @user = User.find(session[:user_id])
        end
    end


    def index
        render "home_page"
    end
end

# def add_tour()
#     tour = Tour.new
#     tour.tour_code = gets.chomp
#     tour.from = gets.chomp
#     tour.to = gets.chomp
#     tour.day = gets.chomp
#     tour.start_time = gets.chomp
#     tour.end_time = gets.chomp
#     tour.passenger_limit = gets.chomp.to_i
#     tour.price = gets.chomp.to_f
#     tour.save   
# end

app/controllers/login_controller.rb
class LoginController < ApplicationController

    def new
    end

    def create
        user = User.find_by(user_name: params[:user_name])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to tours_path
        else
            flash[:error] = "Invalid user name or password"
            redirect_to sign_in_path
        end
    end

    def logout
        session[:user_id] = nil
        redirect_to sign_up_path, notice: "Logged Out"
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(userParams)
        if @user.save
            session[:user_id] = @user_id
            flash[:success] = "Successfully created account"
            redirect_to sign_in_path
        else
            flash[:error] = "Something went wrong"
            redirect_to sign_up_path
        end
    end

    private

    def userParams
        params.require(:user).permit(:user_name, :gender, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(user_name: params[:user_name])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            puts "hello " + user.user_name
            redirect_to tours_path
        else
            flash[:error] = "Invalid user_name or password"
            redirect_to sign_in_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to sign_up_path, notice: "Logged Out"
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    before_action :checkUser

    def checkUser
        if session[:user_id]==nil
            redirect_to sign_up_path, notice: "Logged Out"
        else
            @user = User.find(session[:user_id])
        end
    end

    def showUserTickets 
        @tickets = @user.tickets
    end

    def showAllTickets
        @all_tickets = Ticket.all
    end
end

app/controllers/tours_controller.rb
class ToursController <  ApplicationController
    before_action :checkUser

    def checkUser
        if session[:user_id]==nil
            redirect_to sign_up_path, notice: "Logged Out"
        else
            @user = User.find(session[:user_id])
        end
    end

    def showAllTour
        @tours = Tour.all
        @tickets = Ticket.all
        # puts @tours[0]
        render "show_all"
    end

    def showTour
        puts params
        @chosen_tour = Tour.find(params[:param])
        render "showTour"
    end

    def bookTicketWithoutCompanion
        tour = Tour.find(params[:param])
        user = User.find(session[:user_id])
        if tour.passenger_limit == 0
            flash[:error] = "Tour is completely booked!"
        redirect_to tours_path
        else
            new_ticket = Ticket.new
            new_ticket.user_id = user.id
            new_ticket.tour_id = tour.id

            new_ticket.save
        end
        flash[:success] = "Successfully Booked Ticket for " + tour.tour_code.to_s
        tour.passenger_limit = tour.passenger_limit - 1
        tour.save
        redirect_to tours_path
    end

    def bookTicketWithCompanion
        tour = Tour.find(params[:param])
        user = User.find(session[:user_id])
        
        if tour.passenger_limit == 0
            flash[:error] = "Tour is completely booked!"
            redirect_to tours_path
        else
            new_ticket = Ticket.new
            new_ticket.user_id = user.id
            new_ticket.tour_id = tour.id

            if Companion.find_by(tour_id: tour.id, gender: user.gender).present?
                companion_to_remove = Companion.find_by(tour_id: tour.id, gender: user.gender)
                
                ticket_to_update = Ticket.find(companion_to_remove.ticket_id)
                ticket_to_update.companion_user_name = user.user_name
                ticket_to_update.save

                new_ticket.companion_user_name = User.find(companion_to_remove.user_id).user_name
                new_ticket.save
                companion_to_remove.delete
            else
                companion_to_add = Companion.new
                
                new_ticket.save
                
                companion_to_add.gender = user.gender
                companion_to_add.tour_id = tour.id
                companion_to_add.user_id = user.id
                companion_to_add.ticket_id = new_ticket.id
                companion_to_add.save
            end
            flash[:success] = "Successfully Booked Ticket for " + tour.tour_code.to_s
            tour.passenger_limit = tour.passenger_limit - 1
            tour.save
            redirect_to tours_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/new.html.erb
<div class="ms-5 mt-5 me-5">
    <h1>Sign In</h1>
    <div class="text-center">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: 'alert alert-info' %>
      <% end %>
    </div>
    <%= form_with url: admin_path do |form|%>
        <div class="mb-3">
            <%= form.label :user_name %>
            <%= form.text_field :user_name, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= form.label :password %>
            <%= form.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= form.submit "LogIn", class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/homepage/home_page.html.erb
<div class="ms-5 mt-5 me-5">
    <h1> Welcome <%= @user.user_name %> </h1>

    <%= button_to 'Book Tour',  tours_path, method: :get %>
    <br>
    <%= button_to 'See Ticket',  tickets_path, method: :get %>
    <br>

    <br>
    <div class="btn btn-dark">
        <%= button_to 'Log Out',  logout_path, method: :post %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookTour</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/login/new.html.erb
<div class="ms-5 mt-5 me-5">
    <h1>Sign In</h1>
    <div class="text-center">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: 'alert alert-info' %>
      <% end %>
    </div>
    <%= form_with url: sign_in_path do |form|%>
        <div class="mb-3">
            <%= form.label :user_name %>
            <%= form.text_field :user_name, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= form.label :password %>
            <%= form.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= form.submit "LogIn", class: "btn btn-primary" %>
        </div>
    <% end %>
    <h6>Don't have an account?</h6>
    <%= link_to '<button type="button" class="btn btn-primary">Sign Up</button>'.html_safe, sign_up_path %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
        <img src="https://img.icons8.com/emoji/2x/waving-hand-light-skin-tone.png" alt="Welcome Image" width="30" height="24" class="d-inline-block align-text-top">
    </a>
    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Book Tour", tours_path, class: "nav-link", method: :get %>
        </li>
        <li class="nav-item">
          <%= link_to 'See Ticket',  tickets_path, class: "nav-link", method: :get %>
        </li>
        <li class="nav-item">
          <%= @user.is_admin ? ( link_to 'See All Ticket',  all_tickets_path, class: "nav-link" ) : "" %>
        </li>
      </ul>
    </div>
    <div id="navbarNav">
        <ul class="navbar-nav justify-content-end collapse navbar-collapse">
            <li class="nav-item">
                <div class= "nav-link" data-toggle="tooltip" data-html="true" title= "User Id => <%= @user.id.to_s %> and gender => <%= @user.gender.eql?("m") ? "Male": "Female" %>" >
                    Welcome <%= @user.user_name %>
                </div>
            </li>
            <li class="nav-item">
            <%= @user.is_admin ? (button_to 'Log Out',  logout_admin_path, method: :post) : (button_to 'Log Out',  logout_path, method: :post) %>
            </li>
        </ul>
    </div> 
  </div>
</nav>

app/views/tickets/showAllTickets.html.erb
<%= render partial: "shared/navbar" %>
<div class="ms-5 mt-5 me-5">
  <h1> All Tickets </h1>

  <table class="table table-striped">
    <tr>
      <th>Ticket Code</th>
      <th>From </th>
      <th>To </th>
      <th>Tour Code</th>
      <th>User Name </th>
      <th>Gender</th>
      <th>Companion User Name</th>
    </tr>

  <% @all_tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.id %></td>
      <td><%= ticket.tour.from %></td>
      <td><%= ticket.tour.to %></td>
      <td><%= ticket.tour.tour_code %></td>
      <td><%= ticket.user.user_name%></td>
      <td><%= ticket.user.gender.eql?("m") ? "Male": "Female" %></td>
      <td><%= ticket.companion_user_name %></td>
      </tr>
  <% end %>
  </table>
</div>

app/views/tickets/showUserTickets.html.erb
<%= render partial: "shared/navbar"%>
<div class="ms-5 mt-5 me-5">
  <h1> My Tickets </h1>

  <table class="table table-striped">
    <tr>
      <th>Ticket Code</th>
      <th>From </th>
      <th>To </th>
      <th>Tour Code</th>
      <th>Companion User Name</th>
    </tr>

  <% @tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.id %></td>
      <td><%= ticket.tour.from %></td>
      <td><%= ticket.tour.to %></td>
      <td><%= ticket.tour.tour_code %></td>
      <td><%= ticket.companion_user_name %></td>
      </tr>
  <% end %>
  </table>
</div>

app/views/tickets/show_all.html.erb
<%= render partial: "shared/navbar"%>
<div class="ms-5 mt-5 me-5">
  <h1> My Tickets </h1>

  <table class="table table-striped">
    <tr>
      <th>Ticket Code</th>
      <th>From </th>
      <th>To </th>
      <th>Tour Code</th>
      <th>Companion User Name</th>
    </tr>

  <% @tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.id %></td>
      <td><%= ticket.tour.from %></td>
      <td><%= ticket.tour.to %></td>
      <td><%= ticket.tour.id %></td>
      <td><%= ticket.companion_user_name %></td>
      </tr>
  <% end %>
  </table>
</div>

app/views/tours/showTour.html.erb
<%= render partial: "shared/navbar"%>
<div class="text-center">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: 'alert alert-info' %>
      <% end %>
</div>

<div class="ms-5 mt-5 me-5">
    <h1> Tour </h1>
    <table class="table table-striped">
        <tr>
            <th>Tour Code</th>
            <th>From </th>
            <th>To </th>
            <th>Day</th>
            <th>Price</th>
        </tr>
        <tr>
            <td><%= @chosen_tour.tour_code %></td>
            <td><%= @chosen_tour.from %></td>
            <td><%= @chosen_tour.to %></td>
            <td><%= @chosen_tour.day %></td>
            <td><%= @chosen_tour.price %></td>
        </tr>
    </table>
    <div class="container mb-3">
            <div class="row row-cols-auto">
                <%= button_to 'Book with Companion', tours_with_companion_path(param:@chosen_tour.id), class: "btn btn-primary" %>
                <%= button_to 'Book without Companion', tours_without_companion_path(param:@chosen_tour.id), class: "btn btn-warning" %>
            </div>
    </div>
</div>

app/views/tours/show_all.html.erb
<%= render partial: "shared/navbar"%>
<div class="text-center">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: 'alert alert-info' %>
      <% end %>
</div>
<div class="ms-5 mt-5 me-5">
    <h1> Tour List </h1>
    <table class="table table-striped">
    <tr>
        <th>Tour Code</th>
        <th>From </th>
        <th>To </th>
        <th>Day</th>
        <th>Price</th>
        <th>Status</th>
    </tr>

    <% @tours.each do |tour| %>
        <tr>
            <td><%= tour.tour_code %></td>
            <td><%= tour.from %></td>
            <td><%= tour.to %></td>
            <td><%= tour.day %></td>
            <td><%= tour.price %></td>
            <td><%= @tickets.find_by(user_id: session[:user_id], tour_id: tour.id).present? ? "Already booked" : (link_to '<button type="button" class="btn btn-secondary">Book</button>'.html_safe, chosen_tour_path(param:tour)) %> </td>
        </tr>
    <% end %>
    </table>
</div>